# Generated by Django 6.0.4 on 2026-08-04 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_staff_alter_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time when this account was created.', verbose_name='creation date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='email_verified',
            field=models.BooleanField(default=False, help_text="Designates whether the user's email is verified.", verbose_name='email verified'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
