# Generated by Django 6.0.4 on 2026-09-25 08:42

import colorfield.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
                ('hex_value', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='email',
        ),
        migrations.AddField(
            model_name='shop',
            name='contact_information',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='shop',
            name='opening_hours',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=32)),
                ('manufacturer_country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('size_system', models.CharField(choices=[('alpha', 'Alpha'), ('numeric', 'Numeric')], max_length=7, null=True)),
                ('sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('colors', models.ManyToManyField(to='shops.color')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
    ]
