# Generated by Django 6.0.4 on 2026-09-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_color_remove_shop_email_shop_contact_information_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ('id',)},
        ),
    ]
