# Generated by Django 6.0.4 on 2026-09-27 07:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_color_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='longitude',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('tops', 'Tops'), ('bottoms', 'Bottoms'), ('dresses', 'Dresses'), ('outerwear', 'Outerwear'), ('underwear', 'Underwear'), ('accessories', 'Accessories'), ('others', 'Others')], default='others', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='shop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, geography=True, srid=4326),
            preserve_default=False,
        ),
    ]
